@host=https://localhost:7197

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName":"Amichail",
    "lastName":"Mantinband",
    "email":"amichai@mantinband.com",
    "password":"Amiko1234!"
}

###

